### ISSUE TITLE
Uploadcare Fails to Build in Xcode 6.2

### ISSUE THREAD

**Issue by ksylvest** [uploadcare/uploadcare-ios#10]
The dependency `AQGridView` fails with the following error:

    Too many arguments to function call, expected 0, have 4.

Probably shouldn't even use a `AQGridView` given `UICollectionView`

**Comment by Rusik** [comment]
Closed due new library version 3.0
